# Generated by Django 2.1.8 on 2019-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=25)),
                ('foodimage', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
